apiVersion: v1
kind: Service
metadata:
  name: hello-page
  labels:
    app: hello-page
    service: hello-page
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: NodePort
  selector:
    app: hello-page
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-page
  labels:
    app: hello-page
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-page
        version: v1
    spec:
      containers:
      - name: hello-page
        image: canxing/hello-page:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: HELLO_SERVICE
          value: hello.com
        - name: HELLO_PORT
          value: "80"
